### ISSUE TITLE
Takes over Editor role

### ISSUE THREAD

**Issue by Trenbania** [strangerstudios/pmpro-membership-manager-role#4]
When I enabled this on a Multisite, it replaces the Editor role, rather than adding an extra role.

**Comment by Trenbania** [comment]
In addition, I'm a super admin, but can no longer edit users withe the role of Editor!

**Comment by andrewlimaza** [comment]
I'm not sure but this should fix part of your issue -> https://github.com/strangerstudios/pmpro-membership-manager-role/pull/5
